"""add token usage columns to messages and eval_case_results

Revision ID: 6a5f90d6a7bb
Revises: 8ab38bfb4aa5
Create Date: 2026-10-08 13:41:31.875854

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6a5f90d6a7bb'
down_revision: str | None = '8ab38bfb4aa5'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eval_case_results', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('eval_case_results', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'completion_tokens')
    op.drop_column('messages', 'prompt_tokens')
    op.drop_column('eval_case_results', 'completion_tokens')
    op.drop_column('eval_case_results', 'prompt_tokens')
    # ### end Alembic commands ###
