"""add device_hash to users and quota_usage table

Revision ID: 99518fe58104
Revises: 2fb2c374fb20
Create Date: 2026-10-02 01:19:31.840721

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '99518fe58104'
down_revision: str | None = '2fb2c374fb20'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', 'day', name='uq_quota_usage_scope_key_day')
    )
    op.create_index(op.f('ix_quota_usage_key'), 'quota_usage', ['key'], unique=False)
    op.add_column('users', sa.Column('device_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_device_hash'), 'users', ['device_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_device_hash'), table_name='users')
    op.drop_column('users', 'device_hash')
    op.drop_index(op.f('ix_quota_usage_key'), table_name='quota_usage')
    op.drop_table('quota_usage')
    # ### end Alembic commands ###
